PHOTO_PRODUCT_1 = {0: 'AgACAgIAAxkBAAIBnmYJuNPv3uo_DHGbL8Yjozl6pEqqAAIX4DEbRJJQSKQGa-hBNKMXAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIBn2YJuNuXd__hSRlAKau7WetG8xgSAAIU4DEbRJJQSKXbJjWZucISAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIBoGYJuN0dbloHJpp_Enb4IDPY0ccwAAIY4DEbRJJQSFJngyx6o9e3AQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIBoWYJuOGuX6q_TfR3kdgcOwW9PIVOAAIZ4DEbRJJQSP7dsDew9BrrAQADAgADcwADNAQ'}

PHOTO_PRODUCT_2 = {0: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   1: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   2: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   3: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA'}

PHOTO_PRODUCT_3 = {0: ''}

PHOTO_PRODUCT_7 = {0: 'AgACAgIAAxkBAAIBrmYJu6E4ZFy5ixZ7kUwtgCvgL6wzAAI34DEbRJJQSAr1EkT4gCZdAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIBr2YJu6jANlzn4hKpJ4U1Ju1fu_oVAAI44DEbRJJQSD-2nCRYlHgNAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIBsGYJu7HNne4rtE8G0hjOfykLGoqNAAI54DEbRJJQSCsSuu29eWVXAQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIBsWYJu7veQhnxP8M-RF8iPLBgFt9FAAI64DEbRJJQSInUO6gtTo6DAQADAgADcwADNAQ',
                   4: 'AgACAgIAAxkBAAIBsmYJu8F4IVguCRs8E9qQ800ySIUMAAI74DEbRJJQSBy9emVfqZ2BAQADAgADcwADNAQ'}
