PHOTO_PRODUCT_1 = {0: 'AgACAgIAAxkBAAIBnmYJuNPv3uo_DHGbL8Yjozl6pEqqAAIX4DEbRJJQSKQGa-hBNKMXAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIBn2YJuNuXd__hSRlAKau7WetG8xgSAAIU4DEbRJJQSKXbJjWZucISAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIBoGYJuN0dbloHJpp_Enb4IDPY0ccwAAIY4DEbRJJQSFJngyx6o9e3AQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIBoWYJuOGuX6q_TfR3kdgcOwW9PIVOAAIZ4DEbRJJQSP7dsDew9BrrAQADAgADcwADNAQ'}

PHOTO_PRODUCT_2 = {0: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   1: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   2: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA',
                   3: 'AgACAgIAAxkBAAIFTmYTCLLOsKAf13QSNUSVTSCU-dUAA6TYMRsJSZhIHoh8GtOObDMBAAMCAANzAAM0BA'}

PHOTO_PRODUCT_3 = {0: 'AgACAgIAAxkBAAIH02YT23UAAdq3f15voDwF3gMo0HUZIQACYdYxGwlJoEhA0JKlOyZCGwEAAwIAA3MAAzQE',
                   1: 'AgACAgIAAxkBAAIH1GYT23q_Qkpuxur8A5c5mm8fzx5YAAJi1jEbCUmgSHh-wjn9_un-AQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIH1WYT23xDCfMk9oBKHEbVu0eLaqxdAAJj1jEbCUmgSIe8Hl6K7zgyAQADAgADcwADNAQ'}

PHOTO_PRODUCT_4 = {0: 'AgACAgIAAxkBAAIGq2YT1Hh2XzsUMngojMFlphs8lbh8AAJN1jEbCUmgSISmtDPOP7LsAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIGrGYT1HqlzOt__hGDOJTKSVPxRU1hAAJO1jEbCUmgSHOXdKWesfVKAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIGrWYT1HyESfTmxUYxTnNE4zjj1DbHAAJP1jEbCUmgSIOdyL0bLY_iAQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIGrmYT1IChLBMJKI3ntLSo76AdmbOAAAJQ1jEbCUmgSNF_ozZT5f3rAQADAgADcwADNAQ',
                   4: 'AgACAgIAAxkBAAIHgmYT2oTELYxl_JRGTpFxcxKZj3h_AAJ91jEbCUmgSJgSrKHuk6_JAQADAgADcwADNAQ'}

PHOTO_PRODUCT_5 = {0: 'AgACAgIAAxkBAAIIoGYT3-yk8LatobYZf5vJ1pBBIPJiAAKM1jEbCUmgSEZ31qHjYk_5AQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIIoWYT3-yT_BmmiTScT5FCxG3sdLyxAAKN1jEbCUmgSEWGX52FkolHAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIIomYT3-zBidR6DmOSJol5Jy53i3MDAAKO1jEbCUmgSKYPmaXZZ5zOAQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIIo2YT3-5V9EQDfFl1j3K8SooRXQUdAAKP1jEbCUmgSNUq5XZOc_ZBAQADAgADcwADNAQ',
                   4: 'AgACAgIAAxkBAAIIpGYT3_DB-MZV8UFLvn4NL7-ws39JAAKQ1jEbCUmgSL9cFod9zQNRAQADAgADcwADNAQ',
                   5: 'AgACAgIAAxkBAAIIpWYT3_OyqQ7EBiFO5JIhIvQIL3VsAAKR1jEbCUmgSNoCQN7mbInJAQADAgADcwADNAQ'}

PHOTO_PRODUCT_6 = {0: 'AgACAgIAAxkBAAIIjmYT3t7DHAXP1jGSE6SOLEWK_EnzAALJ3zEbLeGgSMNfX0GlHMBoAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIIj2YT3uC3tER0zGL_um2JvCGwY76LAALK3zEbLeGgSFp432JBbtTUAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIIkGYT3uLcoMVHZd18Hq3btD9tF2ExAALL3zEbLeGgSJF06-4yktWnAQADAgADcwADNAQ'}

PHOTO_PRODUCT_7 = {0: 'AgACAgIAAxkBAAIBrmYJu6E4ZFy5ixZ7kUwtgCvgL6wzAAI34DEbRJJQSAr1EkT4gCZdAQADAgADcwADNAQ',
                   1: 'AgACAgIAAxkBAAIBr2YJu6jANlzn4hKpJ4U1Ju1fu_oVAAI44DEbRJJQSD-2nCRYlHgNAQADAgADcwADNAQ',
                   2: 'AgACAgIAAxkBAAIBsGYJu7HNne4rtE8G0hjOfykLGoqNAAI54DEbRJJQSCsSuu29eWVXAQADAgADcwADNAQ',
                   3: 'AgACAgIAAxkBAAIBsWYJu7veQhnxP8M-RF8iPLBgFt9FAAI64DEbRJJQSInUO6gtTo6DAQADAgADcwADNAQ',
                   4: 'AgACAgIAAxkBAAIBsmYJu8F4IVguCRs8E9qQ800ySIUMAAI74DEbRJJQSBy9emVfqZ2BAQADAgADcwADNAQ'}
